### ISSUE TITLE
2.8 release breaks macro on classes extending BaseElement

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/laravel-html#71]
The 2.8 release notes mention this:

> Added a magic __call method that responds to methods ending with If, so any method can be called with a condition as it's first argument. The method will only be applied if the condition is truthy.

### Problem

Apparently this breaks a macro I've set up for the Input, Textarea, etc classes that can be extended using mixins. Works fine on 2.7. Upgrade to 2.8 returns the following error:

<img width="447" alt="screen shot 2018-01-05 at 19 00 30" src="https://user-images.githubusercontent.com/711940/34622018-b2aa8230-f24b-11e7-938e-6ecfe69760fc.png">

> ErrorException (E_ERROR)
Type error: Too few arguments to function Spatie\Html\BaseElement::__call(), 1 passed in /vagrant/vendor/spatie/laravel-html/src/BaseElement.php on line 406 and exactly 2 expected (View: …)

### Example

```php
Input::mixin(new FormErrorClass);
```

```php
<?php

declare(strict_types=1);

namespace App\Mixins\Html;

class FormErrorClass
{
    /**
     * Automatically mark an input field as invalid when it contains an error.
     *
     * @return \Closure
     */
    public function highlightOnError()
    {
        return function () {
            if (session('errors') && session('errors')->has($this->getAttribute('name'))) {
                return $this->class('form-error');
            }

            return $this;
        };
    }
}
```

Was using it like this in my Blade views (which just adds the error class if the input is found in the session's error data):

```php
{{ html()->text('phone_number')->class('form__input')->required()->attribute('maxlength', 80)->placeholder('Your phone number')->highlightOnError() }}
```

### Solution

A temporary solution would be to:

- Downgrade to 2.7 (currently doing so)
- Pass an empty array to the `highlightOnError` method so the `__call` function is satisfied

### Exceptions

This works fine:

```php
Html::mixin(new FormErrorElement);

// and then

{{ html()->formError('name') }}
```

**Comment by sebastiandedeyne** [comment]
I've never used mixins, so I'm not completely following yet. Where does `__call` get called with less arguments exactly? Do you have a full stackrace?

**Comment by sebastiaanluca** [comment]
A mixin function is practically the same as `Input::macro()`, but I should try and test it with a regular macro just to be sure.

So this works fine:

```php
{{ html()->text('phone_number') }}
```

This does too:

```php
// Note the empty array to satisfy the `__call` method parameters
{{ html()->text('phone_number')->highlightOnError([]) }}
```

This does not (works in 2.7 and before):

```php
{{ html()->text('phone_number')->highlightOnError() }}
```

`highlightOnError()` (a macro function) is called and —since 2.8— passed through the `__call` method which requires additional parameters. I'll try and get you a full stack trace on Monday, hope the above can be of aid in the meantime.

**Comment by sebastiandedeyne** [comment]
I think I see what's wrong, I shouldn't be spreading the arguments at `BaseElement` L402.

Could you remove the spread, so...

```php
return $this->__macro_call($name, $arguments);
```

...and see if that resolves the issue?

https://github.com/spatie/laravel-html/blob/b1d438aee81e3913b253d338bef907433c657222/src/BaseElement.php#L402

**Comment by sebastiaanluca** [comment]
Yep, that fixes it :)

**Comment by sebastiandedeyne** [comment]
Cool, I’ll push a fix tomorrow :)

**Comment by sebastiandedeyne** [comment]
Released a patch version that should fix this!

**Comment by sebastiaanluca** [comment]
Thanks for the quick fix! 🙌
